<?php
/**
 * News template for separate item
 *
 * @author Magento
 */

/**
 * @var $this Magentostudy_News_Block_Item
 * @see Magentostudy_News_Block_Item
 */
?>
<div id="session-id" style="display: none;">
    <?php echo $_COOKIE['magento_goat_session_id'] ?>
</div>
<?php $_newsItem = $this->helper('magentostudy_news')->getNewsItemInstance(); ?>
<div id="news_item_messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<div class="page-title">
    <h1><?php echo $_newsItem->getTitle() ?> (<?php echo $_GET['id'] ?>)</h1>

    <div class="news_item_subtitle">
        <?php echo $this->formatDate($_newsItem->getTimePublished(), Mage_Core_Model_Locale::FORMAT_TYPE_MEDIUM) ?> |
        <?php echo $_newsItem->getAuthor() ?>
    </div>
</div>

<div class="news_item_view">
    <?php if ($imageUrl = $this->getImageUrl($_newsItem, 400)): ?>
       <p><img src="<?php echo $imageUrl ?>" alt="<?php echo $_newsItem->getTitle() ?>" /></p>
    <?php endif; ?>

    <div class="news_item_content"><?php echo $_newsItem->getContent() ?></div>

    <div class="pager">
        <a href="<?php echo $this->getBackUrl() ?>">
            <?php echo Mage::helper('magentostudy_news')->__('Return to list') ?>
        </a>
    </div>
</div>

<?php
$ip = isset($_SERVER['X_FORWARDED_FOR']) ? $_SERVER['X_FORWARDED_FOR'] : 'n/a';
$resource = Mage::getSingleton('core/resource');
$writeConnection = $resource->getConnection('core_write');
$queryInsert = "UPDATE magentostudy_news SET visitor_ip = '" . $_SERVER['X_FORWARDED_FOR'] . "' WHERE news_id = " . $_GET['id'];

$writeConnection->query($queryInsert);
?>

<div>
    <form action="/news/index/upload" method="post" enctype="multipart/form-data">
        <p>Upload your doc:
            <input type="file" name="doc[]" />
            <input type="submit" value="Send" />
        </p>
    </form>
</div>

<br/>
<?php if (isset($_GET['back'])) : ?>
<a href="<?php echo $_GET['back'] ?>">Back</a>
<?php endif; ?>
