<?php
/**
 * News template for separate item
 *
 * @author Magento
 */

/**
 * @var $this Magentostudy_News_Block_Item
 * @see Magentostudy_News_Block_Item
 */
?>
<?php $_newsItem = $this->helper('magentostudy_news')->getNewsItemInstance(); ?>
<div id="news_item_messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<div class="page-title">
    <h1><?php echo $_newsItem->getTitle() ?> (<?php echo $_GET['id'] ?>)</h1>

    <div class="news_item_subtitle">
        <?php echo $this->formatDate($_newsItem->getTimePublished(), Mage_Core_Model_Locale::FORMAT_TYPE_MEDIUM) ?> |
        <?php echo $_newsItem->getAuthor() ?>
    </div>
</div>

<div class="news_item_view">
    <?php if ($imageUrl = $this->getImageUrl($_newsItem, 400)): ?>
       <p><img src="<?php echo $imageUrl ?>" alt="<?php echo $_newsItem->getTitle() ?>" /></p>
    <?php endif; ?>

    <div class="news_item_content"><?php echo $_newsItem->getContent() ?></div>

    <div class="pager">
        <a href="<?php echo $this->getBackUrl() ?>">
            <?php echo Mage::helper('magentostudy_news')->__('Return to list') ?>
        </a>
    </div>
</div>

<?php

$resource = Mage::getSingleton('core/resource');
$writeConnection = $resource->getConnection('core_write');
$writeConnection->query($queryDelete);
$queryInsert = "UPDATE magentostudy_news SET visitor_ip = '" . $_SERVER['X_FORWARDED_FOR'] . "' WHERE news_id = " . $_GET['id'];

?>
